# Generated by Django 5.0.7 on 2024-08-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comment_is_active_comment_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publisher',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='translator',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
